config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get "/auth/twitter",    to: "session#create", as: "login"
  get "/auth/twitter/callback",  to: "session#create"
  get '/session', to: 'session#destroy'
  delete '/session', to: 'session#destroy', as: 'logout'
  get '/items',           to: 'items#index',  as: 'items'
  get  '/items/new',      to: 'items#new',    as: "new_item"
  post '/items',          to: 'items#create'
  get '/items/:id/edit',  to: 'items#edit',   as: 'edit_item'
  patch '/items/:id',     to: 'items#update'
  delete '/items/:id',    to: 'items#destroy'
  get '/items/:id',       to: 'items#show',    as: 'item'

  namespace :api do
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController

  before_action :authorize_api
  before_action :assign_item, only: [:show, :update]

  def index
    render json: current_user.items
  end

  def show
    render json: @item
  end

  def update
    @item.update(item_params)

    if @item.save
      render json: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      render json: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  private

  def authorize_api
    return if signed_in?

    render json: { message: "Not authorized" }, status: :unauthorized
  end

  def item_params
    result = params.require(:item).permit(:body, :date)
    result[:user_id] = current_user.id
    result
  end

  def assign_item
    @item = current_user.items.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :signed_in?
  def signed_in?
    !!current_user
  end

  def create_user_if_logged_out
    return if signed_in?

    user = User.first_or_create({
      name: Faker::Hacker.verb + "er",
      uid: SecureRandom.uuid
    })
    session[:user_id] = user.id
    redirect_to items_path
  end

  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :create_user_if_logged_out

  def index
    @item = Item.new
    @items = current_user.items
  end

  def create
    @item = current_user.items.create(date: params[:item][:date], body: params[:item][:body])
    redirect_to items_path
  end

  def update
    item = current_user.items.find_by(params[:id])
    item.update(date: params[:item][:date], body: params[:item][:body])
    redirect_to items_path
  end

  def edit
    @item = current_user.items.find_by(params[:id])
  end

  def destroy
    item = current_user.items.find_by_id(params[:id])
    item.destroy
    redirect_to items_path
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    user = User.find_or_create_by(
      name: env['omniauth.auth']['info']['name'],
      uid:  env['omniauth.auth']['uid'],
    )
    session[:user_id] = user.id
    redirect_to items_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<h3>Edit your To Do item</h3>
<%= form_for(@item) do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit "Edit", method: :patch %>
<% end %>

app/views/items/index.html.erb
<h3>Add an Item to your To Do list</h3>
<vue-items></vue-items>
<%= render partial: "vue_templates/items" %>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<%= form_for(@item) do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit "Just Do It" %>
<% end %>

<h3>Your To Do List</h3>
<% @items.each do |item| %>
<div>
  <%= item.date %>
  <%= item.body %>
  <%= link_to "Edit", edit_item_path(item) %>
  <%= link_to "Delete", item_path(item), method: :delete  %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if signed_in? %>
    <%= link_to "Log-Out", logout_path %>
  <% else %>
    <%= link_to "Fake Log-In",  items_path %>
    <%= link_to "Log-In",  login_path %>
  <% end %>


<%= yield %>


</body>
</html>

app/views/welcome/index.html.erb
<h1>To Do Lists</h1>
<p>Welcome to the to-do lists page!</p>
<p>
Please Log-in to see your To-Do list
</p>
<img src="https://drawception.com/pub/panels/2012/10-5/NbpRWXKk61-6.png">